### PR TITLE
Add datapacks as a honorary mention for save directory edits

### PR DESCRIPTION
**Pull request by Lupus590**
I've avoided backticks so that it's not as eye catching.

### CODE REVIEW

**Comment by SquidDev** [comment]
This makes the message longer than 2k characters, which is too long. We had to cut it down in #41 too.

**Comment by SquidDev** [comment]
Also:

> however this can cause CC computers to disconnect from rom, rebooting them fixes this.

[Citation needed](https://github.com/cc-tweaked/CC-Tweaked/issues?q=is%3Aissue+is%3Aopen+datapack)

**Comment by Lupus590** [comment]
I've had it happen in my (now quite old) single-player world, it also didn't always happen I think.

**Comment by Lupus590** [comment]
That char count is very mean.

Now I feel what others probably do when they complain about discords API

**Pull request closed without merging**
